### ISSUE TITLE
OAuth2 support (feature request)

### ISSUE THREAD

**Issue by mooomooo** [smhaller/ldap-overleaf-sl#32]
Include an option to instead use an OAuth2 identitiy provider--i.e. gitlab or github--for registration / login.

**Comment by VPaulV** [comment]
Would like to vote for this feature as well

**Comment by yzx9** [comment]
I am actively working on OAuth2 support in [my fork](https://github.com/yzx9/ldap-overleaf-sl/tree/feature/oauth2), referencing the approach used in [sustech/overleaf-ldap-oauth2](https://mirrors.sustech.edu.cn/git/sustech-cra/overleaf-ldap-oauth2/) as a guide.

I'm uncertain if it's fully operational yet, I would greatly appreciate any assistance in testing it.

- [ ] code
  - [x] basic
  - [x] disable OAuth2 by default (to ensure that this PR does not introduce any breaking changes)
  - [x] configuration
  - [x] state support
  - [ ] disable LDAP
- [ ] test
  - [x] GitHub
  - [ ] KeyCloak
  - [ ] Authentik (thanks to @VPaulV ) 
- [ ] docs

Example configuration for Github:

```
OAUTH2_CLIENT_ID: YOUR_CLIENT_ID
OAUTH2_CLIENT_SECRET: YOUR_CLIENT_SECRET
OAUTH2_SCOPE: YOUR_SCOPE
OAUTH2_AUTHORIZATION_URL: https://github.com/login/oauth/authorize
OAUTH2_TOKEN_URL: https://github.com/login/oauth/access_token
OAUTH2_PROFILE_URL: https://api.github.com/user
OAUTH2_USER_ATTR_EMAIL: email
OAUTH2_USER_ATTR_UID: id
OAUTH2_USER_ATTR_FIRSTNAME: name
OAUTH2_USER_ATTR_LASTNAME:
OAUTH2_USER_ATTR_IS_ADMIN: site_admin
```

**Comment by VPaulV** [comment]
Thank you so much! I cannot help with development, but definitely can do testing. Is it stable enough to test already?
Will try today after work

**Comment by VPaulV** [comment]
Sorry for the delay, for some reason cannot make my docker-compose work with the new version. I will report back once figure out the issue

**Comment by yzx9** [comment]
> Sorry for the delay, for some reason cannot make my docker-compose work with the new version. I will report back once figure out the issue

~~I am encountering issues with integrating GitHub OAuth2; it's not functioning as expected. Currently, we can observe a log of `{ "msg":"successful log in" }` and a subsequent redirection to `/project`. However, we are then redirected back and receive a log stating `{ "msg":"user not logged in so redirecting to login page" }`. I am uncertain about what has happened, but I suspect it may be related to the `SessionManager`.~~

**Update**: Upon further investigation, I've determined that the issue is not related to the code. Instead, it was a misconfiguration in ShareLaTeX specific to my development environment. Disabling the `SHARELATEX_SECURE_COOKIE` and `SHARELATEX_BEHIND_PROXY` settings ([a30419e](https://github.com/yzx9/ldap-overleaf-sl/commit/a30419ea5aefe7836ac162918cc0a1aaca24f960)) resolved the issue, and everything is now functioning as expected.

**Comment by VPaulV** [comment]
Alright, was able to make docker compose work with the new version. So far cannot setup OAuth2 to work. I am using Authentik here is my setup:
```
      OAUTH2_CLIENT_ID: redacted
      OAUTH2_CLIENT_SECRET: redacted
      OAUTH2_AUTHORIZATION_URL: https://auth.redacted.domain/application/o/authorize/
      OAUTH2_TOKEN_URL: https://auth.redacted.domain/application/o/token/
      OAUTH2_PROFILE_URL: https://auth.redacted.domain/application/o/userinfo/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overleaf-secured1.rule=Host(`overleaf.redacted.domain`)"
      - "traefik.http.routers.overleaf-secured1.tls=true"
      - "traefik.http.routers.overleaf-secured1.tls.certresolver=myresolver"
      - "traefik.http.routers.overleaf-secured1.entrypoints=websecure"
      - "traefik.http.services.overleaf-secured1.loadbalancer.server.port=80"
      ## SSO 
      - "traefik.http.routers.overleaf-secured1.middlewares=chain-authentik@file"
```

But after successful login in authentik I get to the login page of overleaf again. So I cannot even get the behavior you have. Am I missing something in my configuration?

**Comment by VPaulV** [comment]
Alright, was able to make docker compose work with the new version. So far cannot setup OAuth2 to work. I am using Authentik here is my setup:
```
      OAUTH2_CLIENT_ID: redacted
      OAUTH2_CLIENT_SECRET: redacted
      OAUTH2_AUTHORIZATION_URL: https://auth.redacted.domain/application/o/authorize/
      OAUTH2_TOKEN_URL: https://auth.redacted.domain/application/o/token/
      OAUTH2_PROFILE_URL: https://auth.redacted.domain/application/o/userinfo/
      OAUTH2_SCOPE: email
      OAUTH2_USER_ATTR_EMAIL: email
      OAUTH2_USER_ATTR_UID: username
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overleaf-secured1.rule=Host(`overleaf.redacted.domain`)"
      - "traefik.http.routers.overleaf-secured1.tls=true"
      - "traefik.http.routers.overleaf-secured1.tls.certresolver=myresolver"
      - "traefik.http.routers.overleaf-secured1.entrypoints=websecure"
      - "traefik.http.services.overleaf-secured1.loadbalancer.server.port=80"
      ## SSO 
      - "traefik.http.routers.overleaf-secured1.middlewares=chain-authentik@file"
```

But after successful login in authentik I get:
```
The request fails due to a missing, invalid, or mismatching redirection URI (redirect_uri).
```
Probably should change authentik config somehow, it worked with the original overleaf-ldap-oauth2 implementation tho

```
GET
https://auth.redacted.domain/application/o/authorize/?response_type=code&client_id=redacted&redirect_uri=https://overleaf.redacted.domain/oauth/callback&scope=email
[HTTP/2 400 Bad Request 47ms]

	
GET
	https://auth.redacted.domain/application/o/authorize/?response_type=code&client_id=redacted&redirect_uri=https://overleaf.redacted.domain/oauth/callback&scope=email
Status
400
Bad Request
VersionHTTP/2
Transferred1.89 kB (4.51 kB size)
Referrer Policysame-origin
Request PriorityHighest

    	
    content-encoding
    	gzip
    content-length
    	1516
    content-type
    	text/html; charset=utf-8
    date
    	Thu, 23 Nov 2023 14:42:51 GMT
    referrer-policy
    	same-origin
    vary
    	Accept-Encoding
    vary
    	Accept-Encoding
    vary
    	Cookie
    x-authentik-id
    	redacted
    x-content-type-options
    	nosniff
    X-Firefox-Spdy
    	h2
    x-frame-options
    	DENY
    x-powered-by
    	authentik
    	
    Accept
    	text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	en-US,en;q=0.5
    Connection
    	keep-alive
    Cookie
    	authentik_proxy=redacted
    DNT
    	1
    Host
    	auth.redacted.domain
    Sec-Fetch-Dest
    	document
    Sec-Fetch-Mode
    	navigate
    Sec-Fetch-Site
    	same-site
    Sec-Fetch-User
    	?1
    TE
    	trailers
    Upgrade-Insecure-Requests
    	1
    User-Agent
    	Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0
Uncaught SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
    <anonymous> https://auth.redacted.domain/application/o/authorize/?response_type=code&client_id=redacted&redirect_uri=https://overleaf.redacted.domain/oauth/callback&scope=email:23
authorize:23:22
```

**Comment by VPaulV** [comment]
Here is output of auth system after successful authorization with the old 3.2 version
```
{
    "flow": "redacted",
    "scopes": "email profile openid",
    "http_request": {
        "args": {
            "client_id": "redacted",
            "redirect_uri": "https://overleaf.redacted.domain/oauth/callback",
            "response_type": "code"
        },
        "path": "/api/v3/flows/executor/default-provider-authorization-implicit-consent/",
        "method": "GET"
    },
    "authorized_application": {
        "pk": "redacted",
        "app": "authentik_core",
        "name": "Overleaf",
        "model_name": "application"
    }
}
User
{
    "pk": 7,
    "email": "redacted",
    "username": "redacted"
}
```

**Comment by VPaulV** [comment]
Ah alright, the problem with `redirection URI`, was on my side. I had to update allowed URL in Authentik. So now, it successfully redirects to `https://overleaf.redacted.domain/oauth/callback`, but login is not working; after successful  redirect I get back to the overleaf login page

**Comment by VPaulV** [comment]
Here is how it looks like after I clicked on `Log in via OAuth` and successfully logged in:
![image](https://github.com/smhaller/ldap-overleaf-sl/assets/5863225/618f3932-15d0-4079-8c9d-4663e7f533be)

Please let me know if I can provide any logs

**Comment by yzx9** [comment]
> Here is how it looks like after I clicked on `Log in via OAuth` and successfully logged in: ![image](https://user-images.githubusercontent.com/5863225/285254416-618f3932-15d0-4079-8c9d-4663e7f533be.png)
> 
> Please let me know if I can provide any logs

@VPaulV Thanks for your report. I have updated a configuration related to this issue, as noted in my previous comment, which may help in resolving it.

Upon reviewing your configuration, I didn't find any obvious errors. To provide further assistance, could you please supply a detailed log by following these steps:

1. Set the env variable `LOG_LEVEL` to `debug` (default is info - you can do this in the docker-compose file)
2. Check the logs in ShareLaTeX, particularly at `/var/log/sharelatex/web.log`. You can do this by using the command: `docker exec ldap-overleaf-sl cat /var/log/sharelatex/web.log`.

**Comment by VPaulV** [comment]
Here is the error I get from web.log

```
{"name":"web","hostname":"5177a9051959","pid":164,"level":20,"responseTimeMs":8,"req":{"method":"GET","url":"/oauth/redirect","remoteAddress":"172.18.0.1","headers":{"referer":"https://overleaf.redacted.domain/login","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"}},"res":{"statusCode":302,"headers":{"content-length":"444"}},"msg":"GET /oauth/redirect","time":"2023-11-24T16:37:38.494Z","v":0}
OAuth2 code de333fede95242bba2a34619e03dba13
OAuth2 respond {"error":"invalid_client","error_description":"Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)"}
Fails to access by OAuth2: SyntaxError: Unexpected end of JSON input
```

**Comment by VPaulV** [comment]
Here is the error I get from web.log

```
{"name":"web","hostname":"5177a9051959","pid":164,"level":20,"responseTimeMs":8,"req":{"method":"GET","url":"/oauth/redirect","remoteAddress":"172.18.0.1","headers":{"referer":"https://overleaf.redacted.domain/login","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"}},"res":{"statusCode":302,"headers":{"content-length":"444"}},"msg":"GET /oauth/redirect","time":"2023-11-24T16:37:38.494Z","v":0}
OAuth2 code redacted
OAuth2 respond {"error":"invalid_client","error_description":"Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)"}
Fails to access by OAuth2: SyntaxError: Unexpected end of JSON input
```

**Comment by VPaulV** [comment]
Here is the error I get from web.log

```
{"name":"web","hostname":"5177a9051959","pid":164,"level":20,"responseTimeMs":8,"req":{"method":"GET","url":"/oauth/redirect","remoteAddress":"172.18.0.1","headers":{"referer":"https://overleaf.redacted.domain/login","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"}},"res":{"statusCode":302,"headers":{"content-length":"444"}},"msg":"GET /oauth/redirect","time":"2023-11-24T16:37:38.494Z","v":0}
OAuth2 code redacted
OAuth2 respond {"error":"invalid_client","error_description":"Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)"}
Fails to access by OAuth2: SyntaxError: Unexpected end of JSON input
```

And in Authentik I see such error:
```
server-1      | {"auth_via": "session", "event": "/api/v3/flows/executor/default-provider-authorization-implicit-consent/?query=response_type%3Dcode%26client_id%redacted%26redirect_uri%3Dhttps%253A%252F%252Foverleaf.redacted.domain%252Foauth%252Fcallback%26scope%3Demail", "host": "auth.redacted.domain", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 64231, "remote": "80.142.236.135", "request_id": "bbf4cb02ab884ea6a436a21023df6941", "runtime": 40, "scheme": "https", "status": 200, "timestamp": "2023-11-24T17:08:06.711763", "user": "redacted", "user_agent": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"}

server-1      | {"auth_via": "unauthenticated", "client_id": "", "event": "OAuth2Provider does not exist", "host": "auth.redacted.domain", "level": "warning", "logger": "authentik.providers.oauth2.views.token", "pid": 64231, "request_id": "854aeb148eda4606924f5ca87a494362", "timestamp": "2023-11-24T17:08:06.789901"}
```
So far provider exists 100%, and works with other services i.e original oauth sharelatex 3.2 implementation...

**Comment by yzx9** [comment]
> Here is the error I get from web.log
> 
> ```
> {"name":"web","hostname":"5177a9051959","pid":164,"level":20,"responseTimeMs":8,"req":{"method":"GET","url":"/oauth/redirect","remoteAddress":"172.18.0.1","headers":{"referer":"https://overleaf.redacted.domain/login","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"}},"res":{"statusCode":302,"headers":{"content-length":"444"}},"msg":"GET /oauth/redirect","time":"2023-11-24T16:37:38.494Z","v":0}
> OAuth2 code redacted
> OAuth2 respond {"error":"invalid_client","error_description":"Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)"}
> Fails to access by OAuth2: SyntaxError: Unexpected end of JSON input
> ```

@VPaulV It appears we're facing an API compatibility issue. Our current setup uses a request consumption code in JSON format, but Authentik seems not to support JSON. To address this, I have added support for `content-type: application/x-www-form-urlencoded` and set it as the default. Could you please test it again to see if this resolves the issue?

**Comment by VPaulV** [comment]
@yzx9 Thank you for the update. Now authentik can see it indeed, still cannot login tho, please see logs attached
```
{"name":"web","hostname":"1bcdac0a4c74","pid":165,"level":20,"responseTimeMs":6,"req":{"method":"GET","url":"/oauth/redirect","remoteAddress":"172.18.0.1","headers":{"referer":"https://overleaf.domain.redacted/login","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"}},"res":{"statusCode":302,"headers":{"content-length":"484"}},"msg":"GET /oauth/redirect","time":"2023-11-24T19:30:37.521Z","v":0}
OAuth, receive code redacted and state 49nmoG
OAuth2 respond {"access_token":"partially_redacted.eyJpc3MiOiJodHRwczovL2dhdGUuY2hmLmhvdXNlL2FwcGxpY2F0aW9uL28vb3ZlcmxlYWYvIiwic3ViIjoicGF1bCIsImF1ZCI6InNOVHdpUmM0UnhOdmFnNTdtakV2VEJud2VLRnFrdlp5NzE4aEhQdXYiLCJleHAiOjE3MDA4NTQ1MzgsImlhdCI6MTcwMDg1NDIzOCwiYXV0aF90aW1lIjoxNzAwODU0MTkyLCJhY3IiOiJnb2F1dGhlbnRpay5pby9wcm92aWRlcnMvb2F1dGgyL2RlZmF1bHQiLCJlbWFpbCI6InBhdWxAY2hmLmhvdXNlIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF6cCI6InNOVHdpUmM0UnhOdmFnNTdtakV2VEJud2VLRnFrdlp5NzE4aEhQdXYiLCJ1aWQiOiJsTWN2STg4bXd0dVo0U0VnVThOWm0wN0ZMRWM4dGg2V2x6SHFSVkVWIn0.JKCHihLs61e0Jfzi6jqwBit5PrSsC-A_Lc9oFGJa_nYHV-ummPSHREBiRFZ-gFBnhsNEhnCUq7ydb3Ma9UYXtb2-R59lovs4dxqe6FvkCUvoXX6J0lv9_so8vneToqYWi_Zi6-i9D3aMDocdvGNgZJ-OwA01ufoylnTYpCTz6RZgtqDv2AccOEYBv70o3X0XMoAJ47EmJUvgU5fSphLFW2Msk3-kp6VwGFlxFhf-MqOdgV1dSGlaLvnpw0mnSC9alAHboYplvW2Z_j69AzhCfI2sJ3rkLCfd2yzo5jQBockdh6BfoSp-0yzi2gjVlsRt3UxBxTz5QBn5oy3vN5DtJ0tgJmHjbheLt__yNQd_WazCy1sLM8fgCCkDHB4ZdfY8Au758SRzRURVNgar71DHPswwCsmqFb_r0Xpd4DCDTefYTKiiOB1snffguxKjQnUrHTDLATePuuZonjj0Gl5WuQzGql9uytGAC6284fLa45BJT-22RjPcL5vd54d3SQE0cxjihNLdTsW7WUeMwtk4qq_q-kDkCz8yDwTcW_a_csM9jaD1TLzn4I-KbN2g6GSbDrdXvhRa1vumjitlHZZzhDBwqFksma6jncmN_IAsLc1lLxyEblpi5w_OJrL4quEAyK23w1tRyDk3OPSx_DnqEQ9StAP8hYgv4PLkWKmpCZE","refresh_token":"93Lq5rxvFGcgEn1Itr0mG9FzjbLBZtw91zT673wKnLVrE0dTAxTKnqpP6cqSumydmDeIOa4BftMggSH6SSBR8I2aV6KFCgJWR1F3fM6tP6OPcUXh92pXZzkb7Dhec9hC","token_type":"Bearer","expires_in":300,"id_token":"partially_redacted.eyJpc3MiOiJodHRwczovL2dhdGUuY2hmLmhvdXNlL2FwcGxpY2F0aW9uL28vb3ZlcmxlYWYvIiwic3ViIjoicGF1bCIsImF1ZCI6InNOVHdpUmM0UnhOdmFnNTdtakV2VEJud2VLRnFrdlp5NzE4aEhQdXYiLCJleHAiOjE3MDM0NDYyMzgsImlhdCI6MTcwMDg1NDIzOCwiYXV0aF90aW1lIjoxNzAwODU0MTkyLCJhY3IiOiJnb2F1dGhlbnRpay5pby9wcm92aWRlcnMvb2F1dGgyL2RlZmF1bHQiLCJhdF9oYXNoIjoiYk9DSVoxT1NvVVNXOGMyejh1dHVtUSIsImVtYWlsIjoicGF1bEBjaGYuaG91c2UiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZX0.l8iS4i3RNF8OCbPNrv4cKc_kYtku9AnWttnLVkhX_uaVK1OQ--yvFvDuq99Tbar2NrfqsIgrECk52Se1g--wrU3YZaOSTeNl_TGTfvyprEzFoz8FFWbI63MrYLz1_T8KSxREenqug_GyDraZUxFueKDudmpo9BH72XjBY-5NH9dhc3d3bQk9XON1vBwHxzIpO4VCYJ5ZvX61K7iZEutn_aG5dxCSYk3mYpua1xEh_yyPVmvPcxvr_FydnJ80-9ofahX-l_R19JbyzNUCR8-1N_BjuTSRv2YzogkYv7jFtZNye-aW4oXV-Tp3x_Vh3VVhomZ4oKhdGhU8jmtVOLjc7Ks02GrCQ-N1gF94oVk1wSsxgS1SFseWQMt86WgUclwMAH-renKF7zaGVAFkx8qhM4aW0c3aCkuKMvq4-ClgIGUqXAea6GMk1MymHX4UF5_6nRl8cAHCpc4YapM7RUKiUQxN0ozIQg28jlOmLIKq61_AaBgBkjI7H-FI_Vjrju3OaD2_W3RZKRlxUBI-Z52rM1OmESbheR4txZJQs4oLFnW0zrERmjGaZUMWDM6OnfaFYgs6VMWrvqmgT7UBfu-ZQqOM0JW2eVNQiydumHx_LNa47JsRuEa1y-rqBoMrGFZ7GNqOeJv_R9mMgj5NCfNqAiGmLF9rL6_T9emqSTcKm60"}
Fails to access by OAuth2: SyntaxError: Unexpected end of JSON input
{"name":"web","hostname":"1bcdac0a4c74","pid":165,"level":20,"responseTimeMs":411,"req":{"method":"GET","url":"/oauth/callback?code=659b26a4aa8c4aa7a2353dae45bb5064&state=49nmoG","remoteAddress":"172.18.0.1","headers":{"user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"}},"res":{"statusCode":302,"headers":{"content-length":"56"}},"msg":"GET /oauth/callback?code=659b26a4aa8c4aa7a2353dae45bb5064&state=49nmoG","time":"2023-11-24T19:30:38.464Z","v":0}
{"name":"web","hostname":"1bcdac0a4c74","pid":165,"level":20,"responseTimeMs":9,"req":{"method":"GET","url":"/login","remoteAddress":"172.18.0.1","headers":{"user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"}},"res":{"statusCode":200,"headers":{"content-length":"8027"}},"msg":"GET /login","time":"2023-11-24T19:30:38.506Z","v":0}
{"name":"web","hostname":"1bcdac0a4c74","pid":165,"level":20,"rss":"165.35","heapTotal":"87.10","heapUsed":"76.33","external":"20.13","arrayBuffers":"18.12","msg":"process.memoryUsage()","time":"2023-11-24T19:31:21.719Z","v":0}


```

**Comment by VPaulV** [comment]
I added some extra log output to see how exactly response looks like 
```
content-encoding: gzip
content-length: 23
content-type: text/html; charset=utf-8
date: Fri, 24 Nov 2023 23:58:37 GMT
referrer-policy: same-origin
vary: Accept-Encoding, Accept-Encoding, Cookie
www-authenticate: error="insufficient_scope", error_description="The request requires higher privileges than provided by the access token"
x-authentik-id: 1d6f4301434e49a3892c937e93e990f2
x-content-type-options: nosniff
x-frame-options: DENY
x-powered-by: authentik
Raw response:  
Fails to access by OAuth2: TypeError: Body is unusable
```

**Comment by VPaulV** [comment]
It works!
Example configuration for Authentik:
```
      OAUTH2_ENABLED: "true"
      OAUTH2_AUTHORIZATION_CONTENT_TYPE: "application/x-www-form-urlencoded"
      OAUTH2_CLIENT_ID: "redacted"
      OAUTH2_CLIENT_SECRET: "redacted"
      OAUTH2_AUTHORIZATION_URL: "https://auth.redacted.domain/application/o/authorize/"
      OAUTH2_TOKEN_URL: "https://auth.redacted.domain/application/o/token/"
      OAUTH2_PROFILE_URL: "https://auth.redacted.domain/application/o/userinfo/"
      OAUTH2_USER_ATTR_EMAIL: "email"
      OAUTH2_USER_ATTR_UID: "email"
      OAUTH2_USER_ATTR_FIRSTNAME: "name"
      #to make it work one should create a custom scope first
      OAUTH2_USER_ATTR_IS_ADMIN: "is_admin"

```

Thank you for the implementation!

**Comment by VPaulV** [comment]
I have a problem to setup admin account tho. I have added is_admin attribute and added to config
```
 OAUTH2_USER_ATTR_IS_ADMIN: "is_admin"
 ```
 Now, when I logging with admin account I still don't get admin account in sharelatex. 
 I can confirm that is_admin exist and set to True, here is log output
 ```
 OAuth2 user profile {"email":"admin@redacted.domain","email_verified":true,"is_admin":true,"name":"redacted","given_name":"redacted","preferred_username":"redacted","nickname":"redacted","groups":["authentik Admins"],"sub":"redacted"}
 ```
Maybe OAUTH2_USER_ATTR_IS_ADMIN expects not boolean values?

---
UPD: It actually works, but only after a second login. So, to access the admin account, one needs to log out after the first login and then log in again

**Comment by VPaulV** [comment]
I also would like to confirm that your implementation perfectly works with version 4.1.6

**Comment by mooomooo** [comment]
It works with Gitlab!

Settings:
```
      ## OAuth2 Settings
      OAUTH2_ENABLED: "true"
      OAUTH2_PROVIDER: Gitlab
      OAUTH2_CLIENT_ID: XXX
      OAUTH2_CLIENT_SECRET: XXX
      OAUTH2_SCOPE: read_user
      OAUTH2_AUTHORIZATION_URL: https://git.${DOMAIN}/oauth/authorize
      OAUTH2_TOKEN_URL: https://git.${DOMAIN}/oauth/token
      OAUTH2_PROFILE_URL: https://git.${DOMAIN}/api/v4/user
      OAUTH2_USER_ATTR_EMAIL: email
      OAUTH2_USER_ATTR_UID: id
      OAUTH2_USER_ATTR_FIRSTNAME: name
      OAUTH2_USER_ATTR_LASTNAME:
      OAUTH2_USER_ATTR_IS_ADMIN: is_admin
```
