### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by chf0x** [smhaller/ldap-overleaf-sl#52]
Hi guys. Thank you for the great project. After setting everything up and following the readme, I am getting a `502 Bad Gateway error` when trying to reach the login page. I can confirm that MongoDB and Redis are started and working properly. In the Docker Compose logs, there are no errors on start, and I can see that the database is replicated properly.

I found the following error in the Nginx error logs:
```
2024/04/20 22:33:57 [error] 178#178: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.9, server: _, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:4000/", host: "overleaf.domain.com"

```

Then I went into the Docker container and found that indeed there is nothing on port 4000:
```
root@21f28f798e58:/overleaf/services/web# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:3003          0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:3036          0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:3005          0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:3009          0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:3010          0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:3042          0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:3013          0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:3016          0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:3048          0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:3049          0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:3054          0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      163/nginx: master p 
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      163/nginx: master p 
tcp        0      0 127.0.0.11:34353        0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:3026          0.0.0.0:*               LISTEN      -                   
tcp6       0      0 :::10843                :::*                    LISTEN      -                   
tcp6       0      0 :::3100                 :::*                    LISTEN      -                   
udp        0      0 127.0.0.11:51903        0.0.0.0:*                           -                  
```

Here is what I found in `/var/log/sharelatex/web.log`. Could this error be related to my issue?
```
Node.js v18.18.2
Initializing metrics
Set UV_THREADPOOL_SIZE=16
Using default settings from /overleaf/services/web/config/settings.defaults.js
Using settings from /etc/sharelatex/settings.js
/overleaf/node_modules/express/lib/router/route.js:211
        throw new Error(msg);
        ^

Error: Route.post() requires a callback function but got an [object Undefined]
    at Route.<computed> [as post] (/overleaf/node_modules/express/lib/router/route.js:211:15)
    at proto.<computed> [as post] (/overleaf/node_modules/express/lib/router/index.js:521:19)
    at Object.initialize (/overleaf/services/web/app/src/router.js:745:13)
    at Object.<anonymous> (/overleaf/services/web/app/src/infrastructure/Server.js:340:8)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/overleaf/services/web/app.js:31:16)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
```

Thank you in advance! And please let me know if I can provide any additional logs?

**Comment by smhaller** [comment]
hm, 
what are your settings in the `.env` file?
can you post your configuration the docker-compose file
thx

**Comment by chf0x** [comment]
```
version: '3.7'
networks:
  overleaf-external:
    name: webproxy
    external: true
  overleaf-local:
    driver: bridge

services:
  web:
    restart: always
    build: .
    container_name: overleaf_sharelatex
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_started
    links:
      - mongo
      - redis
    networks:
      - "overleaf-local"
      - "overleaf-external"
    volumes:
      - ./nginx_logs:/var/log/nginx/
      - ./sharelatex_data:/var/lib/sharelatex
      - ./sharelatex_packages:/usr/local/texlive
    environment:
      SHARELATEX_APP_NAME: [CUSTOM APP NAME]
      SHARELATEX_MONGO_URL: mongodb://[MONGO_URL]/sharelatex
      SHARELATEX_REDIS_HOST: redis
      REDIS_HOST: redis
      ENABLE_CONVERSIONS: 'true'
      EMAIL_CONFIRMATION_DISABLED: 'true'
      SHARELATEX_SITE_URL: [CUSTOM SITE URL]
      SHARELATEX_NAV_TITLE: [CUSTOM NAV TITLE]
      SHARELATEX_ADMIN_EMAIL: [ADMIN EMAIL]
      SHARELATEX_EMAIL_FROM_ADDRESS: "[FROM EMAIL ADDRESS]"
      SHARELATEX_EMAIL_SMTP_HOST: [SMTP HOST]
      SHARELATEX_EMAIL_SMTP_PORT: [SMTP PORT]
      SHARELATEX_EMAIL_SMTP_SECURE: 'true'
      SHARELATEX_EMAIL_SMTP_USER: [SMTP USER]
      SHARELATEX_EMAIL_SMTP_PASS: [SMTP PASSWORD]
      SHARELATEX_ALLOW_ANONYMOUS_READ_AND_WRITE_SHARING: 'true'
      SHARELATEX_ALLOW_PUBLIC_ACCESS: 'true'
      SHARELATEX_SECURE_COOKIE: "true"
      SHARELATEX_BEHIND_PROXY: "true"
      OAUTH2_ENABLED: "true"
      OAUTH2_AUTHORIZATION_CONTENT_TYPE: "application/x-www-form-urlencoded"
      OAUTH2_CLIENT_ID: [CLIENT ID]
      OAUTH2_CLIENT_SECRET: [CLIENT SECRET]
      OAUTH2_AUTHORIZATION_URL: [AUTHORIZATION URL]
      OAUTH2_TOKEN_URL: [TOKEN URL]
      OAUTH2_PROFILE_URL: [PROFILE URL]
      OAUTH2_SCOPE: ""
      OAUTH2_USER_ATTR_EMAIL: "email"
      OAUTH2_USER_ATTR_UID: "email"
      OAUTH2_USER_ATTR_FIRSTNAME: "name"
      OAUTH2_USER_ATTR_IS_ADMIN: "is_admin"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overleaf-secured.rule=Host(`[CUSTOM HOST]`)"
      - "traefik.http.routers.overleaf-secured.tls=true"
      - "traefik.http.routers.overleaf-secured.tls.certresolver=myresolver"
      - "traefik.http.routers.overleaf-secured.entrypoints=websecure"
      - "traefik.http.services.overleaf-secured.loadbalancer.server.port=80"
      - "traefik.http.routers.overleaf-secured.middlewares=chain-authentik@file,overleaf-sso"
      - "traefik.http.middlewares.overleaf-sso.replacepathregex.regex=^/login"
      - "traefik.http.middlewares.overleaf-sso.replacepathregex.replacement=/oauth/redirect"
      - "traefik.docker.network=webproxy"

  mongo:
    restart: always
    image: mongo:4.4
    container_name: overleaf_mongo
    command: "--replSet overleaf"
    volumes:
      - "./mongo_data:/data/db"
    healthcheck:
      test: "mongo --quiet --eval 'rs.hello().setName ? rs.hello().setName : rs.initiate({_id: \"overleaf\",members:[{_id: 0, host:\"mongo:27017\"}]})'"
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - "overleaf-local"

  redis:
    restart: always
    image: redis:latest
    container_name: overleaf_redis
    networks: 
      - "overleaf-local"
    volumes:
      - ./redis_data:/data

```

Here is my Docker Compose file. Everything was functioning until I upgraded Docker. I attempted to revert to the previous version, but it no longer works.

```
docker -v
Docker version 26.1.2, build 211e74b
```
